WINDOW_DISPLAY_TEXT = "Crappy Birds"

# window size
WINDOW_SIZE_WIDTH = 500
WINDOW_SIZE_HEIGHT = 500
PIPE_WIDTH = 50
GROUND_Y_COORDINATE = 408
GAP_BETWEEN_PIPES = 130
MIN_HEIGHT_OF_PIPE = 70
VELOCITY_OF_PIPES = 8
NEXT_PIPE_ADDITION_GAP = 180
UPDATE_WINDOW_TIME = 25 #50
BIRD_HEIGHT = 30
BIRD_WIDTH = 38
#VELOCITY_OF_BIRD = 10
JUMP_DISTANCE = 6
GRAVITY_FALL_DISTANCE = 15
GAP_TO_COUNT_SCORE = PIPE_WIDTH + 10
BIRD_Y_COORDINATE_MAX = GROUND_Y_COORDINATE - BIRD_HEIGHT + 3
BIRD_Y_COORDINATE_MIN = -3

# INITIAL COORDINATES
BIRD_INITIAL_X = 20
BIRD_INITIAL_Y = 250
NORTH_PIPE_INITIAL_X = 200
NORTH_PIPE_INITIAL_Y = 200
SOUTH_PIPE_INITIAL_X = 400
SOUTH_PIPE_INITIAL_Y = 200
FOREGROUND_INITIAL_X = 0
FOREGROUND_INITIAL_Y = 400
INITIAL_NORTH_PIPES_HEIGHT = [120, 225, 130, 270]
INITIAL_NORTH_PIPES_X = [400, 400+NEXT_PIPE_ADDITION_GAP, 400+NEXT_PIPE_ADDITION_GAP*2, 400+NEXT_PIPE_ADDITION_GAP*3]
INITIAL_NORTH_PIPES_Y = [0, 0, 0, 0]

##### image path #####
BASE_PATH = ".\\resources\\"
RESIZE_IMAGE_NAME_PREFIX = "resized"
IMAGE_RESOURCE_DIRECTORY = "GameObjectsImages\\"
RESIZED_IMAGE_DIRECTORY = IMAGE_RESOURCE_DIRECTORY + "resizedImages\\"

# game object images
BACKGROUND_IMAGE_NAME = IMAGE_RESOURCE_DIRECTORY + "bg2.jpg"
FOREGROUND_IMAGE_NAME = IMAGE_RESOURCE_DIRECTORY + "fg.png"
BIRD_IMAGE_NAME = IMAGE_RESOURCE_DIRECTORY + "bird.png"
FLYING_BIRD_IMAGE_NAME = IMAGE_RESOURCE_DIRECTORY + "birdFlying.png"
PIPE_NORTH_NAME = IMAGE_RESOURCE_DIRECTORY + "windowSizeSouth.png"
PIPE_SOUTH_NAME = IMAGE_RESOURCE_DIRECTORY + "windowSizeNorth.png"

# fonts
EIGHT_BIT_MADNESS_FILE = BASE_PATH + "fonts\\8BitMadness.ttf"


# network constants
RELU_ACTIVATION_FUNCTION = "relu"
IDENTITY_ACTIVATION_FUNCTION = "identity"
SIGMOID_ACTIVATION_FUNCTION = "sigmoid"
SOFTMAX_ACTIVATION_FUNCTION = "softmax"

MAX_POPULATION_SIZE = 100
GENETIC_ALGORITHM_NUMBER_OF_SELECTIONS = 200
GENETIC_LIFE = 10
CROSSOVER_RATE = 0.5
MUTATION_RATE = 0.1
MUTATION_STRENGTH = 0.1
BIRTH_RATE = 0.2
DEATH_RATE = 0.10

FITTEST_BIRD_PICKLE_FILE = BASE_PATH + "fittestBird\\fittestBird.pickle"